/**
 * Build the web demo end-to-end.
 *
 * Artifacts produced in examples/web/dist/:
 *   - hone-editor.wasm        — Perry-compiled WASM binary (raw)
 *   - hone-editor.js          — ESM bundle: Perry bridge + dom-ffi + mount()
 *   - index.html              — minimal demo page consuming hone-editor.js
 *
 * Consumer use:
 *   <script type="module">
 *     import { mount } from './hone-editor.js';
 *     await mount(document.getElementById('editor'), { content: '...', language: 'typescript' });
 *   </script>
 */

import { $ } from 'bun';
import { mkdirSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const HERE = dirname(new URL(import.meta.url).pathname);
const REPO = resolve(HERE, '..', '..');
const DIST = resolve(HERE, 'dist');

mkdirSync(DIST, { recursive: true });

const perryBin = process.env.PERRY ?? 'perry';

console.log('[1/4] perry compile → raw .wasm');
const wasmPath = resolve(DIST, 'hone-editor.wasm');
await $`cd ${REPO} && ${perryBin} compile examples/web/entry.ts --target web --output ${wasmPath}`;

console.log('[2/4] perry compile → .html (to extract bridge)');
const htmlPath = resolve(DIST, 'editor-bundle.html');
await $`cd ${REPO} && ${perryBin} compile examples/web/entry.ts --target web --output ${htmlPath}`;

console.log('[3/4] extract bridge JS from .html');
const html = readFileSync(htmlPath, 'utf8');
// Perry's HTML has two <script> blocks: (1) the bridge (defines bootPerryWasm),
// (2) the boot call (sets __perryWasmB64 and calls bootPerryWasm). We want (1).
const firstScriptStart = html.indexOf('<script>');
if (firstScriptStart === -1) throw new Error('no <script> in Perry HTML');
const firstScriptEnd = html.indexOf('</script>', firstScriptStart);
if (firstScriptEnd === -1) throw new Error('unterminated <script> in Perry HTML');
const bridgeJs = html.slice(firstScriptStart + '<script>'.length, firstScriptEnd);

console.log('[4/5] bundle dom-ffi + tree-sitter bridge → ESM chunks');
async function bundleEsm(entry: string): Promise<string> {
  const b = await Bun.build({
    entrypoints: [entry],
    target: 'browser',
    format: 'esm',
    // web-tree-sitter has a `createRequire` fallback path gated on a Node
    // check — mark "module" external so the bundler doesn't try to follow it.
    // The runtime check (typeof process === 'object') always short-circuits in
    // browsers so the import is never executed.
    external: ['module'],
  });
  if (!b.success) {
    for (const log of b.logs) console.error(log);
    throw new Error('bundle failed: ' + entry);
  }
  return await b.outputs[0].text();
}
const ffiEsm = await bundleEsm(resolve(REPO, 'native/web/dom-ffi.ts'));
const tsBridgeEsm = await bundleEsm(resolve(REPO, 'native/web/tree-sitter-bridge.ts'));
// Strip ESM `export { ... }` from both — we splice their bodies into one
// larger ESM that exposes its own surface through `mount()`.
const stripExports = (s: string) => s.replace(/export\s*\{[^}]*\}\s*;?/g, '');
const ffiInlined = stripExports(ffiEsm);
const tsBridgeInlined = stripExports(tsBridgeEsm);

console.log('[5/5] copy tree-sitter grammar WASMs to dist/');
const grammarFiles = [
  // web-tree-sitter v0.20 ships its runtime as tree-sitter.wasm (not
  // web-tree-sitter.wasm — v0.26 renamed it).
  ['web-tree-sitter/tree-sitter.wasm', 'tree-sitter.wasm'],
  ['tree-sitter-wasms/out/tree-sitter-typescript.wasm', 'tree-sitter-typescript.wasm'],
  ['tree-sitter-wasms/out/tree-sitter-javascript.wasm', 'tree-sitter-javascript.wasm'],
  ['tree-sitter-wasms/out/tree-sitter-python.wasm', 'tree-sitter-python.wasm'],
  ['tree-sitter-wasms/out/tree-sitter-rust.wasm', 'tree-sitter-rust.wasm'],
  ['tree-sitter-wasms/out/tree-sitter-json.wasm', 'tree-sitter-json.wasm'],
  ['tree-sitter-wasms/out/tree-sitter-css.wasm', 'tree-sitter-css.wasm'],
];
for (const [src, name] of grammarFiles) {
  try {
    copyFileSync(resolve(REPO, 'node_modules', src), resolve(DIST, name));
  } catch {
    console.warn('  warn: missing grammar wasm', src);
  }
}

const loaderJs = `// @honeide/editor — web loader.
// Auto-generated by examples/web/build.ts. Do not edit by hand.

// ---- DOM FFI (createDomFfi / createDomFfiCtx) ----
${ffiInlined}

// ---- Tree-sitter bridge (initTreeSitter / createTreeSitterFFI) ----
${tsBridgeInlined}

// ---- Perry bridge (bootPerryWasm + NaN-box runtime) ----
${bridgeJs}

// ---- Consumer API ----

let __wasmBase64Cache = null;

async function loadWasmAsBase64(url) {
  if (__wasmBase64Cache) return __wasmBase64Cache;
  const res = await fetch(url);
  if (!res.ok) throw new Error('failed to fetch ' + url + ': ' + res.status);
  const bytes = new Uint8Array(await res.arrayBuffer());
  // btoa() needs a binary string; chunk to avoid call-stack limits on large WASM.
  let bin = '';
  for (let i = 0; i < bytes.length; i += 0x8000) {
    bin += String.fromCharCode.apply(null, bytes.subarray(i, i + 0x8000));
  }
  __wasmBase64Cache = btoa(bin);
  return __wasmBase64Cache;
}

/**
 * Mount the editor into a DOM element.
 *
 * @param {HTMLElement} el     Container to render into.
 * @param {object} [opts]      Configuration.
 * @param {string} [opts.content]     Initial text content. Default: empty.
 * @param {string} [opts.language]    'typescript' | 'javascript' | 'python' | ... Default: 'typescript'.
 * @param {string} [opts.theme]       'dark' | 'light'. Default: 'dark'.
 * @param {number} [opts.fontSize]    Font size in points. Default: 14.
 * @param {string} [opts.fontFamily]  Font family. Default: 'JetBrains Mono, Menlo, Monaco, monospace'.
 * @param {number} [opts.width]       Editor width in px. Default: container clientWidth or 900.
 * @param {number} [opts.height]      Editor height in px. Default: container clientHeight or 600.
 * @param {boolean} [opts.readOnly]   Disable text input. Default: false.
 * @param {string} [opts.wasmUrl]     URL of hone-editor.wasm. Default: sibling of hone-editor.js.
 * @param {boolean|object} [opts.treeSitter]  Enable tree-sitter syntax highlighting.
 *     true: load grammars for the requested language(s) from sibling URLs.
 *     object: explicit URL map, e.g. { typescript: '...', javascript: '...' }.
 *     false / omit: use keyword tokenizer only.
 *
 * Returns a controller object:
 *   handle              {number}
 *   // overlays
 *   setFindHighlights(json), clearFindHighlights()
 *   setLineDiagnostics(packed), clearDiagnostics()
 *   setBreakpoints(packed), setFoldRanges(packed)
 *   // text I/O + change observation (gh#1)
 *   getText()                       -> string   current buffer text
 *   setText(value)                              replace all text (loads examples / permalinks)
 *   onTextChange(cb)                -> () => void  subscribe to edits; returns unsubscribe
 *   setCursor(line, column)                     0-based; scrolls the line into view
 *   focus()                                     give the editor keyboard focus
 *   // per-range diagnostics: squiggles + hover tooltip (gh#2)
 *   setRangeDiagnostics(json)                   json (string or array) of
 *       [{startLine,startCol,endLine,endCol,severity,message,code?}, …] (0-based)
 *   clearRangeDiagnostics()
 */
export async function mount(el, opts = {}) {
  if (!el || typeof el.appendChild !== 'function') {
    throw new Error('mount: first arg must be a DOM element');
  }
  if (typeof window === 'undefined') {
    throw new Error('mount: requires a browser/DOM environment');
  }
  const wasmUrl = opts.wasmUrl ?? new URL('./hone-editor.wasm', import.meta.url).href;
  // Console filter: silence Perry's verbose mem_call traces (debug instrumentation
  // in wasm_runtime.js:1386 that floods the console).
  if (!window.__honeConsoleFiltered) {
    window.__honeConsoleFiltered = true;
    const orig = console.log.bind(console);
    console.log = function (...args) {
      if (typeof args[0] === 'string' && (args[0].startsWith('mem_call:') || args[0].startsWith('  result:'))) return;
      orig(...args);
    };
  }

  // Initialize tree-sitter first (async, must finish before the WASM boot
  // because entry.ts queries hone_get_init_use_tree_sitter and constructs
  // the engine at module load).
  let tsFns = null;
  const ts = opts.treeSitter;
  if (ts) {
    const base = new URL('./', import.meta.url).href;
    const urls = (typeof ts === 'object') ? ts : {};
    const grammarUrls = {
      webTreeSitter: urls.webTreeSitter ?? base + 'tree-sitter.wasm',
      typescript:    urls.typescript    ?? base + 'tree-sitter-typescript.wasm',
      javascript:    urls.javascript    ?? base + 'tree-sitter-javascript.wasm',
      python:        urls.python        ?? base + 'tree-sitter-python.wasm',
      rust:          urls.rust          ?? base + 'tree-sitter-rust.wasm',
      json:          urls.json          ?? base + 'tree-sitter-json.wasm',
      css:           urls.css           ?? base + 'tree-sitter-css.wasm',
      tsx:           urls.tsx           ?? base + 'tree-sitter-typescript.wasm',
    };
    await initTreeSitter(grammarUrls);
    tsFns = createTreeSitterFFI();
    opts.useTreeSitter = true;
  }

  const ctx = createDomFfiCtx(el, opts);
  // Merge tree-sitter FFI into the dom-ffi object so the WASM module sees both
  // under the same __ffiImports namespace.
  if (tsFns) Object.assign(ctx.ffi, tsFns);
  window.__ffiImports = ctx.ffi;
  const b64 = await loadWasmAsBase64(wasmUrl);
  await bootPerryWasm(b64);
  // Controller methods call the dom-ffi functions directly with the handle
  // captured by createDomFfiCtx — no round-trip through the WASM Editor
  // instance, which lives in a separate JS realm.
  const h = ctx.latestHandle();
  if (h === 0) throw new Error('mount: editor handle was not assigned during boot');
  const ffi = ctx.ffi;
  return {
    handle: h,
    // Overlay setters
    setFindHighlights: (json) => ffi.hone_editor_set_find_highlights(h, json),
    clearFindHighlights: () => ffi.hone_editor_clear_find_highlights(h),
    setLineDiagnostics: (packed) => ffi.hone_editor_set_line_diagnostics(h, packed),
    clearDiagnostics: () => ffi.hone_editor_clear_diagnostics(h),
    setBreakpoints: (packed) => ffi.hone_editor_set_breakpoints(h, packed),
    setFoldRanges: (packed) => ffi.hone_editor_set_fold_ranges(h, packed),
    // Text I/O + change observation (gh#1)
    getText: () => ctx.getText(h),
    setText: (value) => ctx.requestSetText(h, value),
    onTextChange: (cb) => ctx.onTextChange(h, cb),
    setCursor: (line, column) => ctx.requestSetCursor(h, line, column),
    focus: () => ffi.hone_editor_focus(h),
    // Per-range diagnostics: squiggles + hover tooltip (gh#2)
    setRangeDiagnostics: (json) =>
      ffi.hone_editor_set_range_diagnostics(h, typeof json === 'string' ? json : JSON.stringify(json)),
    clearRangeDiagnostics: () => ffi.hone_editor_clear_range_diagnostics(h),
  };
}
`;
writeFileSync(resolve(DIST, 'hone-editor.js'), loaderJs);

// Minimal demo page consumers can copy. Shows runtime opts being passed via
// mount() and the returned controller used to set overlays.
const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>hone-editor — web demo</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html, body { width: 100vw; height: 100vh; overflow: hidden; background: #1e1e1e; }
    #editor { width: 100%; height: 100%; }
  </style>
</head>
<body>
  <div id="editor"></div>
  <script type="module">
    import { mount } from './hone-editor.js';
    const SAMPLE = \`import { TextBuffer } from './buffer';

export class Editor {
  private buffer: TextBuffer;
  private cursorLine: number = 0;

  constructor(content: string) {
    this.buffer = new TextBuffer(content);
  }

  // Insert text at the cursor position
  insert(text: string): void {
    this.buffer.insert(this.cursorLine, text);
  }
}
\`;
    const ed = await mount(document.getElementById('editor'), {
      content: SAMPLE,
      language: 'typescript',
      theme: 'dark',
      fontSize: 14,
      treeSitter: true,
    });
    // Drive the overlay layers to demonstrate them at runtime.
    ed.setFindHighlights('[{"line":2,"col":13,"len":6,"current":1}]');
    ed.setBreakpoints('3\\n7');

    // Per-range diagnostics (gh#2): squiggle the exact span + hover tooltip.
    ed.setRangeDiagnostics([
      { startLine: 4, startCol: 10, endLine: 4, endCol: 20, severity: 2,
        message: 'cursorLine is implicitly typed as number — declare it', code: 'ts(7008)' },
      { startLine: 12, startCol: 24, endLine: 12, endCol: 28, severity: 1,
        message: "Argument of type 'string' is not assignable to parameter of type 'number'", code: 'ts(2345)' },
    ]);

    // Text I/O (gh#1): read the live buffer + observe edits.
    ed.onTextChange((text) => {
      console.log('buffer changed — ' + text.length + ' chars');
    });
    // e.g. read on demand: const source = ed.getText();
    // e.g. jump to a diagnostic: ed.setCursor(12, 24); ed.focus();
  </script>
</body>
</html>
`;
writeFileSync(resolve(DIST, 'index.html'), indexHtml);

// Clean up the intermediate Perry HTML — only the .wasm + .js + index.html ship.
try {
  const { unlinkSync } = await import('node:fs');
  unlinkSync(htmlPath);
} catch {}

const wasmKb = (readFileSync(wasmPath).length / 1024).toFixed(1);
const jsKb = (loaderJs.length / 1024).toFixed(1);
console.log(`✓ dist/hone-editor.wasm  (${wasmKb} KB)`);
console.log(`✓ dist/hone-editor.js    (${jsKb} KB)`);
console.log(`✓ dist/index.html        (open it directly or serve dist/)`);
